// Runtime del compilador: helpers que el código generado importa.
// Separado de `runtime/hmr` para que el cliente sólo pague lo que usa (C.17).

export { ELUR_COMPILER_ABI, __elurAbi } from "./abi.js";
import { effect, mount, type ElurComponent, type ElurMountHandle, type ElurTemplate, type Signal, type TemplateBindingContext, type TemplateDescriptor } from "@elurjs/core";
import * as _coreSignals from "@elurjs/core/signals";
import * as _coreHydrate from "@elurjs/core/hydrate";
import {
  _activateBindingsWithNodes,
  _activateNodeBinding,
  _ensureDelegatedEvent,
  _queueDOMWrite,
  _createKeyedMount,
  _getKeyedSequence,
  _postMountScope,
  _reconcileKeyedList,
  _keyedItemsEqual,
  ELUR_RENDER_PROTOCOL,
  ELUR_TEMPLATE_DESCRIPTOR,
  sanitizeUrl,
  type KEntry,
  type KeyedList,
} from "@elurjs/core/template";
import { _captureContextSnapshot, _withContextSnapshot } from "@elurjs/core/context";

/**
 * Composes a partial attribute value from static literals and dynamic segments.
 *
 * - If no segment is a function, the string is composed once (no effect, no
 *   closure).
 * - If at least one segment is a function (reactive getter), a single reactive
 *   getter is returned. The getter invokes only the function segments and
 *   coerces every segment with `String()`.
 *
 * Generated by the Vite plugin's interpolation transform for partial attribute
 * interpolations like `class="btn ${size} size-${n}"`.
 */
export function __elurCompose(...parts: unknown[]): unknown {
  const read = (v: unknown): string =>
    String(
      typeof v === "function" ? (v as () => unknown)()
        : isSignalLike(v) ? v.value
          : v,
    );
  let reactive = false;
  for (let i = 0; i < parts.length; i++) {
    const p = parts[i];
    // Un signal en un segmento compuesto exige getter: el valor vivo viaja
    // por `.value`, no por la identidad del objeto (`String(sig)` daría
    // "[object Object]").
    if (typeof p === "function" || isSignalLike(p)) {
      reactive = true;
      break;
    }
  }
  if (!reactive) {
    let out = "";
    for (let i = 0; i < parts.length; i++) out += read(parts[i]);
    return out;
  }
  return () => {
    let out = "";
    for (let i = 0; i < parts.length; i++) out += read(parts[i]);
    return out;
  };
}

// =============================================================================
// --- __elurCompiledTemplate: compiled template factory ---
// =============================================================================
// Creates a ElurTemplate from pre-computed static data (html, contexts, pathMap,
// accessPaths). Eliminates detectContext, buildHTML, and both TreeWalkers.

interface CompiledPathMapEntry {
  nodeIndex: number;
  name: string | null;
}

export function __elurCompiledTemplate(
  strings: readonly string[],
  html: string,
  contexts: readonly unknown[],
  pathMap: readonly (CompiledPathMapEntry | null)[],
  resolveNodes: ((frag: DocumentFragment) => Array<Node | null>) | null,
): (values: unknown[]) => ElurTemplate {
  let tpl: HTMLTemplateElement | null = null;

  // Pre-compute maxNodeIndex from pathMap (fallback for when resolveNodes is null)
  let maxNodeIndex = -1;
  for (let i = 0; i < pathMap.length; i++) {
    if (pathMap[i] && pathMap[i]!.nodeIndex > maxNodeIndex) {
      maxNodeIndex = pathMap[i]!.nodeIndex;
    }
  }

  function getTemplate(): HTMLTemplateElement {
    if (tpl) return tpl;
    if (typeof document === "undefined") {
      throw new Error("[elur] DOM rendering requires a document. Use @elurjs/core/server on the server.");
    }
    tpl = document.createElement("template");
    tpl.innerHTML = html;
    return tpl;
  }

  return function (values: unknown[]): ElurTemplate {
    function _render(parent: Node, before: Node | null): () => void {
      const frag = getTemplate().content.cloneNode(true) as DocumentFragment;

      // Resolve nodes — use custom resolver if available, otherwise TreeWalker
      let resolvedNodes: Array<Node | null>;
      if (resolveNodes) {
        resolvedNodes = resolveNodes(frag);
      } else {
        // Fallback: TreeWalker with pre-computed pathMap
        const numBindings = pathMap.length;
        resolvedNodes = new Array(numBindings);
        if (maxNodeIndex > 0) {
          const flatNodes: Node[] = new Array(maxNodeIndex + 1);
          flatNodes[0] = frag;
          const walker = document.createTreeWalker(
            frag,
            NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT
          );
          let fi = 1;
          let currentNode: Node | null;
          while (fi <= maxNodeIndex && (currentNode = walker.nextNode())) {
            flatNodes[fi++] = currentNode;
          }
          for (let i = 0; i < numBindings; i++) {
            const info = pathMap[i];
            resolvedNodes[i] = info ? flatNodes[info.nodeIndex] : null;
          }
        } else if (maxNodeIndex === 0) {
          for (let i = 0; i < numBindings; i++) {
            resolvedNodes[i] = pathMap[i] ? frag : null;
          }
        } else {
          resolvedNodes = new Array(numBindings).fill(null);
        }
      }

      // Activate bindings with pre-resolved nodes — NO second TreeWalker
      const { disposes, postMountHooks } = _activateBindingsWithNodes(
        frag,
        contexts as any[],
        values,
        pathMap as any[],
        resolvedNodes,
      );

      const startMarker = document.createTextNode("");
      const endMarker = document.createTextNode("");
      parent.insertBefore(startMarker, before);
      parent.insertBefore(frag, before);
      parent.insertBefore(endMarker, before);
      postMountHooks.forEach((cb: () => void) => cb());

      return () => {
        for (let i = disposes.length - 1; i >= 0; i--) disposes[i]();
        let node = startMarker.nextSibling;
        while (node && node !== endMarker) {
          const next = node.nextSibling;
          node.parentNode?.removeChild(node);
          node = next;
        }
        startMarker.parentNode?.removeChild(startMarker);
        endMarker.parentNode?.removeChild(endMarker);
      };
    }

    const descriptor: TemplateDescriptor = { version: 1, strings, values, contexts: contexts as TemplateBindingContext[] };

    const elurTemplate: ElurTemplate = {
      __isElurTemplate: true,
      [ELUR_TEMPLATE_DESCRIPTOR]: descriptor,
      _render,
      mount(container: Element | string): ElurMountHandle {
        const el =
          typeof container === "string"
            ? (document.querySelector(container) as Element)
            : container;
        if (!el) {
          throw new Error(`[elur] mount: contenedor no encontrado: ${container}`);
        }
        const cleanup = _render(el, null);
        return { unmount() { cleanup(); } };
      },
    };

    return elurTemplate;
  };
}

type CompiledInstance = ElurTemplate & Record<string, unknown>;
type CompiledRender = (this: CompiledInstance, parent: Node, before: Node | null) => () => void;

export function __elurCreateTemplate(html: string): () => Node {
  let source: Node | null = null;
  return () => {
    if (!source) {
      if (typeof document === "undefined") {
        throw new Error("[elur] DOM rendering requires a document. Use @elurjs/core/server on the server.");
      }
      const template = document.createElement("template");
      template.innerHTML = html;
      source = template.content.firstChild;
      if (!source || source.nextSibling) {
        throw new Error("[elur] Compiled template expected one root node.");
      }
    }
    return source.cloneNode(true);
  };
}

/**
 * C.14 multi-root: el clone devuelve el DocumentFragment completo. El mount
 * inserta el fragment (insertBefore lo vacía) y los comments bounds
 * `elur-fs`/`elur-fe` (first/last child) anclan el remove-por-rango.
 */
export function __elurCreateFragment(html: string): () => DocumentFragment {
  let source: DocumentFragment | null = null;
  return () => {
    if (!source) {
      if (typeof document === "undefined") {
        throw new Error("[elur] DOM rendering requires a document. Use @elurjs/core/server on the server.");
      }
      const template = document.createElement("template");
      template.innerHTML = html;
      source = template.content;
    }
    return source.cloneNode(true) as DocumentFragment;
  };
}

export function __elurCreateTemplatePrototype(
  render: CompiledRender,
  strings: readonly string[],
  contexts: readonly TemplateBindingContext[],
  valueKeys: readonly string[],
  hydrate?: (root: Element, options: unknown, ...values: unknown[]) => () => void,
  ssr?: (emit: unknown, ...values: unknown[]) => AsyncGenerator<unknown, void, unknown>,
  meta?: { blocks?: unknown[]; dev?: string; folded?: number[] },
): CompiledInstance {
  const prototype = {
    __isElurTemplate: true as const,
    _render: render,
    mount(this: CompiledInstance, container: Element | string): ElurMountHandle {
      const element = typeof container === "string"
        ? document.querySelector(container) as Element | null
        : container;
      if (!element) throw new Error(`[elur] mount: contenedor no encontrado: ${container}`);
      const cleanup = this._render(element, null);
      return { unmount: cleanup };
    },
  } as CompiledInstance;

  Object.defineProperty(prototype, ELUR_TEMPLATE_DESCRIPTOR, {
    get(this: CompiledInstance): TemplateDescriptor {
      const values = new Array<unknown>(valueKeys.length);
      for (let i = 0; i < valueKeys.length; i++) values[i] = this[valueKeys[i]];
      const descriptor: TemplateDescriptor = {
        version: 1,
        strings,
        values,
        contexts: contexts as TemplateBindingContext[],
      };
      // C.13: la hydrate compilada se expone en el descriptor — hydrate()
      // la despacha sin scan global y el SSR omite los `data-elur-*`.
      // (Tipo local: el `TemplateDescriptor` del core ≥3.6 lo declara.)
      if (hydrate) {
        (descriptor as {
          hydrate?: (
            r: ParentNode,
            v: readonly unknown[],
            o?: unknown,
            b?: { start: Comment; end: Comment } | null,
          ) => (() => void) | void;
        }).hydrate = (root, vals, options, bounds) =>
            hydrate(__elurHydrateRoot(root, bounds), options, ...vals);
      }
      // C.12 fase 2: renderer SSR especializado — secuencia chunks con
      // strings pre-cortados; la semántica vive en los emit.* del core.
      if (ssr) {
        (descriptor as { ssr?: unknown }).ssr = (emit: unknown, vals: readonly unknown[]) =>
          ssr(emit, ...vals);
      }
      // C.12: metadata serializable de la IR — bloques detectados por el
      // plugin (each/portal), devId, índices plegados. Dev tooling y tests
      // pueden inspeccionar la estructura sin parsear el HTML.
      if (meta) {
        const d = descriptor as {
          blocks?: unknown[];
          dev?: { id: string };
          foldedIndices?: number[];
        };
        if (meta.blocks) d.blocks = meta.blocks;
        if (meta.dev) d.dev = { id: meta.dev };
        if (meta.folded) d.foldedIndices = meta.folded;
      }
      return descriptor;
    },
  });

  return prototype;
}

export function __elurDelegateEvents(events: readonly string[]): void {
  if (typeof document === "undefined") return;
  for (let i = 0; i < events.length; i++) _ensureDelegatedEvent(events[i]);
}

// C.14: escritura de attr namespace-aware. En elementos SVG/MathML:
// - `className` es SVGAnimatedString (readonly) → setAttribute.
// - `xlink:href`, `xml:space`, … → setAttributeNS con su URI.
// El branch usa `namespaceURI` del target — sin cambio de firma/ABI.
const XHTML_NS = "http://www.w3.org/1999/xhtml";
const ATTR_PREFIX_NS: Record<string, string> = {
  xlink: "http://www.w3.org/1999/xlink",
  xml: "http://www.w3.org/XML/1998/namespace",
  xmlns: "http://www.w3.org/2000/xmlns/",
};

function writeAttrValue(target: Element, attrName: string, text: string, isUrl: boolean): void {
  const v = isUrl ? sanitizeUrl(text) : text;
  const isHtml = target.namespaceURI === XHTML_NS || target.namespaceURI == null;
  if (attrName === "class" && isHtml) {
    (target as HTMLElement).className = v;
    return;
  }
  const colon = attrName.indexOf(":");
  if (colon > 0 && !isHtml) {
    const ns = ATTR_PREFIX_NS[attrName.slice(0, colon)];
    if (ns) {
      target.setAttributeNS(ns, attrName, v);
      return;
    }
  }
  target.setAttribute(attrName, v);
}

function removeAttrValue(target: Element, attrName: string): void {
  const colon = attrName.indexOf(":");
  if (colon > 0 && target.namespaceURI !== XHTML_NS && target.namespaceURI != null) {
    const ns = ATTR_PREFIX_NS[attrName.slice(0, colon)];
    if (ns) {
      target.removeAttributeNS(ns, attrName.slice(colon + 1));
      return;
    }
  }
  target.removeAttribute(attrName);
}

export function __elurEvent(
  element: Node,
  eventName: string,
  modifiers: readonly string[],
  handler: unknown,
): void {
  if (typeof handler !== "function") return;
  (element as any)[`__elur_${eventName}`] = handler;
  if (modifiers.length > 0) (element as any)[`__elur_${eventName}_mods`] = modifiers;
}

export function __elurClearEvent(element: Node, eventName: string): void {
  (element as any)[`__elur_${eventName}`] = null;
  (element as any)[`__elur_${eventName}_mods`] = null;
}

export function __elurAttr(
  element: Node,
  attrName: string,
  value: unknown,
  isUrl: boolean,
  executable: boolean,
): (() => void) | null {
  const target = element as Element;
  if (executable) {
    console.warn(
      `[elur] Dynamic binding on executable attribute "${attrName}". Use @event for handlers; avoid binding untrusted values here.`,
    );
  }

  const isDomProp = (
    attrName === "value" || attrName === "checked" || attrName === "selected"
  ) && attrName in target;

  const write = (next: unknown): void => {
    if (isDomProp) {
      (target as any)[attrName] = next ?? "";
    } else if (next == null || next === false) {
      removeAttrValue(target, attrName);
    } else {
      writeAttrValue(target, attrName, String(next), isUrl);
    }
  };

  // Un Signal que llega por el path genérico (clasificación imperfecta o
  // binding compuesto) se suscribe igual que en el path T1 — no stringificar
  // el objeto.
  if (isSignalLike(value)) {
    if (_bindSignalImpl) return _bindSignalImpl(value, write);
    write(value.value);
    return null;
  }

  if (typeof value !== "function") {
    write(value);
    return null;
  }

  let first = true;
  let queued = false;
  let pending: unknown;
  return effect(() => {
    pending = (value as () => unknown)();
    if (first) {
      first = false;
      write(pending);
    } else if (!queued) {
      queued = true;
      _queueDOMWrite(() => {
        queued = false;
        write(pending);
      });
    }
  });
}

export function __elurNode(
  target: Node,
  value: unknown,
  targetIsAnchor: boolean,
  postMountHooks: Array<() => void> | null,
): { dispose: (() => void) | null; hooks: Array<() => void> } | null {
  if (typeof value === "string" || typeof value === "number") {
    const text = String(value);
    if (targetIsAnchor) target.parentNode!.replaceChild(document.createTextNode(text), target);
    else target.textContent = text;
    return null;
  }
  if (value == null || value === false) {
    if (targetIsAnchor) target.parentNode?.removeChild(target);
    return null;
  }

  const anchor = document.createTextNode("");
  if (targetIsAnchor) {
    target.parentNode!.replaceChild(anchor, target);
  } else {
    target.appendChild(anchor);
  }

  const disposes: Array<() => void> = [];
  const hooks = postMountHooks ?? [];
  _activateNodeBinding(anchor, value, disposes, hooks);
  const dispose = disposes.length === 0 ? null : () => {
    for (let i = disposes.length - 1; i >= 0; i--) disposes[i]();
  };
  return { dispose, hooks: postMountHooks ? [] : hooks };
}

export function __elurEffect(fn: () => void): () => void {
  return effect(fn);
}

export function __elurQueue(fn: () => void): void {
  _queueDOMWrite(fn);
}

export function __elurSetAttr(
  element: Node,
  attrName: string,
  value: unknown,
  isUrl: boolean,
  executable: boolean,
): void {
  const target = element as Element;
  if (executable) {
    console.warn(
      `[elur] Dynamic binding on executable attribute "${attrName}". Use @event for handlers; avoid binding untrusted values here.`,
    );
  }
  const isDomProp = (
    attrName === "value" || attrName === "checked" || attrName === "selected"
  ) && attrName in target;
  if (isDomProp) {
    (target as any)[attrName] = value ?? "";
  } else if (value == null || value === false) {
    removeAttrValue(target, attrName);
  } else {
    writeAttrValue(target, attrName, String(value), isUrl);
  }
}

export function __elurNodeFallback(
  text: Text,
  getter: () => unknown,
  postMountHooks: Array<() => void>,
): () => void {
  const connected = text.isConnected;
  const anchor = document.createTextNode("");
  text.parentNode!.replaceChild(anchor, text);
  const disposes: Array<() => void> = [];
  const hooks = connected ? [] : postMountHooks;
  _activateNodeBinding(anchor, getter, disposes, hooks);
  if (connected) {
    for (let i = 0; i < hooks.length; i++) hooks[i]();
  }
  return () => {
    for (let i = disposes.length - 1; i >= 0; i--) disposes[i]();
  };
}

/**
 * Patrón compartido de los writers tipados: primera escritura síncrona al
 * montar; las siguientes pasan por la cola DOM (dedup last-write-wins).
 */
function queueWriter(write: (value: unknown) => void): (value: unknown) => void {
  let first = true;
  let queued = false;
  let pending: unknown;
  return (value: unknown): void => {
    pending = value;
    if (first) {
      first = false;
      write(pending);
    } else if (!queued) {
      queued = true;
      _queueDOMWrite(() => {
        queued = false;
        write(pending);
      });
    }
  };
}

export function __elurAttrWriter(
  element: Node,
  attrName: string,
  isUrl: boolean,
  executable: boolean,
): (value: unknown) => void {
  const target = element as Element;
  if (executable) {
    console.warn(
      `[elur] Dynamic binding on executable attribute "${attrName}". Use @event for handlers; avoid binding untrusted values here.`,
    );
  }
  const isDomProp = (
    attrName === "value" || attrName === "checked" || attrName === "selected"
  ) && attrName in target;
  return queueWriter((pending) => {
    if (isDomProp) {
      (target as any)[attrName] = pending ?? "";
    } else if (pending == null || pending === false) {
      removeAttrValue(target, attrName);
    } else {
      writeAttrValue(target, attrName, String(pending), isUrl);
    }
  });
}

/**
 * F4: writer para attrs HTML que el compilador resuelve en build — sin
 * `namespaceURI`/`indexOf(":")`/sanitización por escritura (sólo se emite
 * para ns html + attr no-URL + no-ejecutable). Semántica idéntica al
 * genérico: prop DOM para value/checked/selected, `class`→`className`,
 * null/false → removeAttribute.
 */
export function __elurAttrWriterHtml(
  element: Node,
  attrName: string,
): (value: unknown) => void {
  const target = element as HTMLElement;
  if (attrName === "class") {
    return queueWriter((v) => {
      if (v == null || v === false) target.removeAttribute("class");
      else target.className = v as string;
    });
  }
  if (
    (attrName === "value" || attrName === "checked" || attrName === "selected") &&
    attrName in target
  ) {
    return queueWriter((v) => {
      (target as any)[attrName] = v ?? "";
    });
  }
  return queueWriter((v) => {
    if (v == null || v === false) target.removeAttribute(attrName);
    else target.setAttribute(attrName, String(v));
  });
}

export function __elurNodeWriter(
  target: Node,
  getter: () => unknown,
  targetIsAnchor: boolean,
  postMountHooks: Array<() => void>,
): { active: boolean; write: (value: unknown) => void; dispose: () => void; mounted: () => void } {
  const text = document.createTextNode("");
  if (targetIsAnchor) target.parentNode!.replaceChild(text, target);
  else target.appendChild(text);

  let mounted = false;
  let first = true;
  let queued = false;
  let pending = "";
  const fallbackDisposes: Array<() => void> = [];
  const writer = {
    active: true,
    write(value: unknown) {
      if (typeof value !== "string" && typeof value !== "number") {
        writer.active = false;
        const anchor = document.createTextNode("");
        text.parentNode!.replaceChild(anchor, text);
        const hooks = mounted ? [] : postMountHooks;
        _activateNodeBinding(anchor, getter, fallbackDisposes, hooks);
        if (mounted) {
          for (let i = 0; i < hooks.length; i++) hooks[i]();
        }
        return;
      }
      pending = String(value);
      if (first) {
        first = false;
        text.data = pending;
      } else if (!queued) {
        queued = true;
        _queueDOMWrite(() => {
          queued = false;
          text.data = pending;
        });
      }
    },
    dispose() {
      for (let i = fallbackDisposes.length - 1; i >= 0; i--) fallbackDisposes[i]();
    },
    mounted() {
      mounted = true;
    },
  };
  return writer;
}

export function __elurReactiveText(
  target: Node,
  getter: () => unknown,
  targetMode: "node" | "parent" | "text",
  postMountHooks: Array<() => void>,
): { dispose: () => void; mounted: () => void } {
  const text = targetMode === "text" ? target as Text : document.createTextNode("");
  if (targetMode === "node") target.parentNode!.replaceChild(text, target);
  else if (targetMode === "parent") target.appendChild(text);

  let mounted = false;
  let fast = true;
  let first = true;
  let queued = false;
  let pending = "";
  const fallbackDisposes: Array<() => void> = [];

  const disposeEffect = effect(() => {
    if (!fast) return;
    const value = getter();
    if (typeof value !== "string" && typeof value !== "number") {
      fast = false;
      const anchor = document.createTextNode("");
      text.parentNode!.replaceChild(anchor, text);
      const hooks = mounted ? [] : postMountHooks;
      _activateNodeBinding(anchor, getter, fallbackDisposes, hooks);
      if (mounted) {
        for (let i = 0; i < hooks.length; i++) hooks[i]();
      }
      return;
    }

    pending = String(value);
    if (first) {
      first = false;
      text.data = pending;
    } else if (!queued) {
      queued = true;
      _queueDOMWrite(() => {
        queued = false;
        text.data = pending;
      });
    }
  });

  return {
    dispose() {
      disposeEffect();
      for (let i = fallbackDisposes.length - 1; i >= 0; i--) fallbackDisposes[i]();
    },
    mounted() {
      mounted = true;
    },
  };
}

interface DirectKeyedEntry {
  node: Node;
  cleanup: () => void;
  /** C.16.4: item que originó la entry — detecta misma-key/objeto-nuevo. */
  item: unknown;
}

/**
 * Repeat especializado — objeto DUAL:
 *
 * - `[ELUR_RENDER_PROTOCOL].mountDom`: mount directo en cliente (el dispatch
 *   de node-binding chequea protocol ANTES que isKeyedList → fast path).
 * - `__isKeyedList` + `keyFn` + `renderFn` + `items` (getter → readItems):
 *   el SSR keyed path lo renderiza con markers `elur-ki:` (renderServer
 *   ausente → cae al path de lista), y la hidratación lo adopta via el
 *   thunk de `__elurHydrateRange` (el effect trackea `items` → reconcile
 *   vivo sin maquinaria nueva).
 *
 * El mismo artefacto corre en cliente, SSR e hidratación (C.12).
 */

/**
 * `moveBefore` (Chrome 133+) mueve un nodo sin desconectarlo — preserva
 * iframes, focus, animaciones y estado de formularios en reorders.
 * Fallback a `insertBefore` donde no exista. Detect una sola vez.
 */
const _elurMoveNode: (parent: Node, node: Node, before: Node | null) => void =
  typeof Element !== "undefined" && "moveBefore" in Element.prototype
    ? (parent, node, before) => (parent as Element).moveBefore(node, before)
    : (parent, node, before) => parent.insertBefore(node, before);

export function __elurCompiledRepeatDirect<T>(
  readItems: () => T[],
  keyFn: (item: T, index: number) => string | number,
  mountRow: (parent: Node, before: Node | null, item: T, index: number) => () => void,
  itemFactory?: (item: T, index: number) => ElurTemplate,
): {
  [ELUR_RENDER_PROTOCOL]: { mountDom(context: { parent: Node; before: Node | null }): () => void };
} & (T extends never ? object : { __isKeyedList?: true; items?: T[] }) {
  const repeat: Record<PropertyKey, unknown> = {
    [ELUR_RENDER_PROTOCOL]: {
      mountDom({ parent, before }: { parent: Node; before: Node | null }) {
        const anchor = before ?? document.createTextNode("");
        if (!before) parent.appendChild(anchor);
        const zoneStart = document.createTextNode("");
        parent.insertBefore(zoneStart, anchor);
        const state = new Map<string | number, DirectKeyedEntry>();
        const prevOrder: Array<string | number> = [];
        const contextSnapshot = _captureContextSnapshot();

        const createEntry = (
          container: Node,
          insertionPoint: Node | null,
          item: T,
          index: number,
        ): DirectKeyedEntry => {
          const cleanup = contextSnapshot.length === 0
            ? mountRow(container, insertionPoint, item, index)
            : _withContextSnapshot(
              contextSnapshot,
              () => mountRow(container, insertionPoint, item, index),
            );
          const node = (insertionPoint ? insertionPoint.previousSibling : container.lastChild)!;
          return { node, cleanup, item };
        };

        /** C.16.4: misma key + objeto nuevo → remount in-place de la fila. */
        const remountEntry = (
          key: string | number,
          i: number,
          items: T[],
          ref: Node | null,
        ): void => {
          const entry = state.get(key)!;
          entry.cleanup();
          entry.node.parentNode?.removeChild(entry.node);
          state.set(key, createEntry(parent, ref, items[i], i));
        };
        const remountIfReplaced = (key: string | number, i: number, items: T[]): void => {
          const entry = state.get(key);
          if (entry && !_keyedItemsEqual(entry.item, items[i])) {
            remountEntry(key, i, items, entry.node.nextSibling);
          }
        };

        const reconcile = (items: T[]): void => {
          // Los mounts de entries nuevas difieren onMount hasta el commit.
          _postMountScope(() => reconcileInner(items));
        };
        const reconcileInner = (items: T[]): void => {
          if (state.size === 0) {
            prevOrder.length = items.length;
            if (items.length > 0) {
              const fragment = document.createDocumentFragment();
              for (let i = 0; i < items.length; i++) {
                const key = keyFn(items[i], i);
                prevOrder[i] = key;
                if (state.has(key)) {
                  console.warn(`[elur] repeat(): duplicate key "${key}". Keys must be unique; the previous entry leaks (orphaned nodes + live effects).`);
                }
                state.set(key, createEntry(fragment, null, items[i], i));
              }
              parent.insertBefore(fragment, anchor);
            }
            return;
          }

          const keyedState = state;
          const newOrder = new Array<string | number>(items.length);
          for (let i = 0; i < items.length; i++) newOrder[i] = keyFn(items[i], i);
          const oldLen = prevOrder.length;
          const newLen = newOrder.length;

          // C.16.2: fast paths — prefix/suffix comunes sin Map/LIS. El trim
          // sólo toma este camino cuando un lado se agota (`pi > pj` =
          // insert-only, `pi > nk` = remove-only) — así el `refNode` del
          // insert siempre apunta a una entry que sobrevivió.
          let pi = 0;
          const minLen = oldLen < newLen ? oldLen : newLen;
          while (pi < minLen && prevOrder[pi] === newOrder[pi]) pi++;
          let pj = oldLen - 1;
          let nk = newLen - 1;
          while (pj >= pi && nk >= pi && prevOrder[pj] === newOrder[nk]) {
            pj--;
            nk--;
          }

          if (pi > pj || pi > nk) {
            // C.16.4: prefix/suffix sobreviven — remount de los que llevan
            // objeto nuevo antes de tocar la ventana media.
            for (let m = 0; m < pi; m++) remountIfReplaced(newOrder[m], m, items);
            for (let m = nk + 1; m < newLen; m++) remountIfReplaced(newOrder[m], m, items);
            if (pi <= pj) {
              if (pi === 0 && pj === oldLen - 1) {
                // Zona entera — sibling walk (Range.deleteContents es
                // patológico en happy-dom sobre zonas grandes).
                let node = zoneStart.nextSibling;
                while (node && node !== anchor) {
                  const next = node.nextSibling;
                  node.parentNode?.removeChild(node);
                  node = next;
                }
                for (const entry of keyedState.values()) entry.cleanup();
                keyedState.clear();
              } else {
                // Ventana contigua [pi..pj]: entries de 1 nodo adyacentes —
                // un solo Range cubre el tramo en vez de removeChild por nodo.
                for (let m = pi; m <= pj; m++) {
                  const n = keyedState.get(prevOrder[m])!.node;
                  n.parentNode?.removeChild(n);
                }
                for (let m = pi; m <= pj; m++) {
                  const key = prevOrder[m];
                  keyedState.get(key)!.cleanup();
                  keyedState.delete(key);
                }
              }
            }
            if (pi <= nk) {
              // Insertar new[pi..nk] antes de la primera entry del suffix
              // (prevOrder[pi] sobrevivió por trim; sin suffix → anchor).
              const refNode = pi < oldLen
                ? keyedState.get(prevOrder[pi])!.node
                : anchor;
              const fragment = document.createDocumentFragment();
              for (let m = pi; m <= nk; m++) {
                const key = newOrder[m];
                const mounted = createEntry(fragment, null, items[m], m);
                if (keyedState.has(key)) {
                  console.warn(`[elur] repeat(): duplicate key "${key}". Keys must be unique; the previous entry leaks (orphaned nodes + live effects).`);
                }
                keyedState.set(key, mounted);
              }
              parent.insertBefore(fragment, refNode);
            }
            prevOrder.length = 0;
            prevOrder.push(...newOrder);
            return;
          }
          const newKeys = new Set<string | number>(newOrder);
          let anySurvive = false;
          for (const key of keyedState.keys()) {
            if (newKeys.has(key)) {
              anySurvive = true;
              break;
            }
          }

          if (!anySurvive) {
            if (keyedState.size > 0) {
              let node = zoneStart.nextSibling;
              while (node && node !== anchor) {
                const next = node.nextSibling;
                node.parentNode?.removeChild(node);
                node = next;
              }
              for (const entry of keyedState.values()) entry.cleanup();
              keyedState.clear();
            }
            if (items.length > 0) {
              const fragment = document.createDocumentFragment();
              for (let i = 0; i < items.length; i++) {
                const key = newOrder[i];
                const mounted = createEntry(fragment, null, items[i], i);
                if (keyedState.has(key)) {
                  console.warn(`[elur] repeat(): duplicate key "${key}". Keys must be unique; the previous entry leaks (orphaned nodes + live effects).`);
                }
                keyedState.set(key, mounted);
              }
              parent.insertBefore(fragment, anchor);
            }
            prevOrder.length = 0;
            prevOrder.push(...newOrder);
            return;
          }

          const keyToNewIndex = new Map<string | number, number>();
          for (let i = 0; i < newOrder.length; i++) keyToNewIndex.set(newOrder[i], i);
          const newToOld = new Int32Array(newOrder.length);
          let moved = false;
          let maxNewIndex = 0;

          for (let i = 0; i < prevOrder.length; i++) {
            const key = prevOrder[i];
            const newIndex = keyToNewIndex.get(key);
            if (newIndex === undefined) {
              const entry = keyedState.get(key)!;
              entry.cleanup();
              keyedState.delete(key);
            } else {
              newToOld[newIndex] = i + 1;
              if (newIndex >= maxNewIndex) maxNewIndex = newIndex;
              else moved = true;
            }
          }

          const sequence = moved ? _getKeyedSequence(newToOld) : [];
          let sequenceIndex = sequence.length - 1;
          let insertionPoint: Node = anchor;

          for (let i = newOrder.length - 1; i >= 0; i--) {
            const key = newOrder[i];
            if (newToOld[i] === 0) {
              const mounted = createEntry(parent, insertionPoint, items[i], i);
              keyedState.set(key, mounted);
              insertionPoint = mounted.node;
            } else {
              let entry = keyedState.get(key)!;
              if (!_keyedItemsEqual(entry.item, items[i])) {
                // C.16.4: misma key + objeto nuevo → remount. Insertar
                // antes de insertionPoint equivale al move a su posición
                // final; se conserva el bookkeeping del LIS.
                remountEntry(key, i, items, insertionPoint);
                entry = keyedState.get(key)!;
                if (moved && sequenceIndex >= 0 && i === sequence[sequenceIndex]) {
                  sequenceIndex--;
                }
                insertionPoint = entry.node;
                continue;
              }
              if (moved) {
                if (sequenceIndex < 0 || i !== sequence[sequenceIndex]) {
                  _elurMoveNode(parent, entry.node, insertionPoint);
                } else {
                  sequenceIndex--;
                }
              }
              insertionPoint = entry.node;
            }
          }

          prevOrder.length = 0;
          prevOrder.push(...newOrder);
        };

        const disposeEffect = effect(() => reconcile(readItems()));
        return () => {
          disposeEffect();
          for (const entry of state.values()) entry.cleanup();
          state.clear();
          zoneStart.parentNode?.removeChild(zoneStart);
          if (!before) anchor.parentNode?.removeChild(anchor);
        };
      },
    },
  };
  if (itemFactory) {
    // Vista KeyedList para SSR (`renderValueChunks` → markers `elur-ki:`)
    // e hidratación (`adoptKeyedRange` → `renderFn` → instancia compilada).
    // `items` es getter: leerlo dentro de un effect rastrea `readItems`.
    repeat.__isKeyedList = true;
    repeat.keyFn = keyFn;
    repeat.renderFn = itemFactory;
    Object.defineProperty(repeat, "items", { get: readItems, enumerable: true });
  }
  return repeat as never;
}

export function __elurCompiledRepeat<T>(
  readItems: () => T[],
  keyFn: (item: T, index: number) => string | number,
  renderFn: (item: T, index: number) => ElurTemplate | ElurComponent,
): { [ELUR_RENDER_PROTOCOL]: { mountDom(context: { parent: Node; before: Node | null }): () => void } } {
  const repeat: Record<PropertyKey, unknown> = {
    // Vista KeyedList para SSR (markers elur-ki:) e hidratación adoptiva —
    // el dispatch de cliente chequea el protocol ANTES → mountDom gana.
    __isKeyedList: true,
    keyFn,
    renderFn,
    [ELUR_RENDER_PROTOCOL]: {
      mountDom({ parent, before }: { parent: Node; before: Node | null }) {
        const anchor = before ?? document.createTextNode("");
        if (!before) parent.appendChild(anchor);
        const zoneStart = document.createTextNode("");
        parent.insertBefore(zoneStart, anchor);
        const state = new Map<string | number, KEntry>();
        const prevOrder: Array<string | number> = [];
        const contextSnapshot = _captureContextSnapshot();
        const mountItem = _createKeyedMount(contextSnapshot);
        const list = {
          __isKeyedList: true as const,
          items: [] as T[],
          keyFn,
          renderFn,
        };

        const disposeEffect = effect(() => {
          list.items = readItems();
          _reconcileKeyedList({
            zoneStart,
            anchor,
            state,
            prevOrder,
            list: list as KeyedList,
            mount: mountItem,
            ctxSnapshot: contextSnapshot,
            onDuplicateKey: (key) => {
              console.warn(`[elur] repeat(): duplicate key "${key}". Keys must be unique; the previous entry leaks (orphaned nodes + live effects).`);
            },
          });
        });

        return () => {
          disposeEffect();
          for (const entry of state.values()) entry.cleanup();
          state.clear();
          let node = zoneStart.nextSibling;
          while (node && node !== anchor) {
            const next = node.nextSibling;
            node.parentNode?.removeChild(node);
            node = next;
          }
          zoneStart.parentNode?.removeChild(zoneStart);
          if (!before) anchor.parentNode?.removeChild(anchor);
        };
      },
    },
  };
  // `items` como getter — leerlo dentro de un effect (hidratación con thunk
  // en `__elurHydrateRange`) trackea `readItems` → reconcile vivo.
  Object.defineProperty(repeat, "items", { get: readItems, enumerable: true });
  return repeat as never;
}

// =============================================================================
// --- C.6 tier T1: bindings directos signal→DOM ---------------------------------
// =============================================================================

// `_bindSignal` es el primitivo T1 del core (edge permanente, sin getter ni
// tracking). Namespace import: en cores antiguos (npm ≤3.5.x) no existe —
// se cae a un effect() equivalente.
const _bindSignalImpl = (_coreSignals as Record<string, unknown>)._bindSignal as
  | (<T>(source: Signal<T>, write: (v: T) => void) => () => void)
  | undefined;

// Duck-type cross-runtime: `instanceof Signal` falla cuando el binding
// vive en otro mundo reactivo (estable vs next-2); `peek` es el marcador
// común de Signal/Computed/ReadonlySignal en los tres.
function isSignalLike(v: unknown): v is Signal<unknown> {
  return (
    typeof v === "object" &&
    v !== null &&
    typeof (v as { peek?: unknown }).peek === "function"
  );
}

/**
 * C.6 T1 texto: `text.data` sigue `sig` sin effect genérico.
 * El compiled code pasa la SEÑAL (no el getter) — escritura inicial al montar
 * + una por cambio real. Si el arg resulta no ser Signal (clasificación
 * estática vs runtime), cae al getter equivalente `() => sig.value` —
 * mismas deps que el arrow original (la cadena de members nunca trackea).
 */
export function __elurBindSignalText(
  text: Text,
  sig: unknown,
): () => void {
  const write = (v: unknown): void => {
    // Sin String(): el setter `data` coacciona igual (WebIDL DOMString).
    text.data = v == null || v === false ? "" : (v as string);
  };
  if (_bindSignalImpl && isSignalLike(sig)) return _bindSignalImpl(sig, write);
  const getter = () => (sig as Signal<unknown> | null)?.value;
  return effect(() => write(getter()));
}

/**
 * C.6 T1 attr: igual para atributos — el writer especializado decide
 * prop vs attribute + sanitización; primera escritura síncrona al montar.
 */
export function __elurBindSignalAttr(
  element: Node,
  attrName: string,
  sig: unknown,
  isUrl: boolean,
  executable: boolean,
): () => void {
  const write = __elurAttrWriter(element, attrName, isUrl, executable);
  if (_bindSignalImpl && isSignalLike(sig)) return _bindSignalImpl(sig, write);
  const getter = () => (sig as Signal<unknown> | null)?.value;
  return effect(() => write(getter()));
}

/** F4 T1: attr HTML resuelto en build — writer sin namespace/URL checks. */
export function __elurBindSignalAttrHtml(
  element: Node,
  attrName: string,
  sig: unknown,
): () => void {
  const write = __elurAttrWriterHtml(element, attrName);
  if (_bindSignalImpl && isSignalLike(sig)) return _bindSignalImpl(sig, write);
  const getter = () => (sig as Signal<unknown> | null)?.value;
  return effect(() => write(getter()));
}

// =============================================================================
// --- C.7 tier T2: expresiones puras con deps estáticas -------------------------
// =============================================================================

export interface ElurDerivedBinding {
  /** Dep única (pack 1-dep — sin array). */
  dep?: unknown;
  /** Deps múltiples (pack N-dep). */
  deps?: unknown[];
  get: () => unknown;
  [key: symbol]: unknown;
}

// Marca del pack T2 — Symbol.for para que el core lo detecte aunque los
// módulos sean copias distintas (plugin runtime vs hydrate/SSR del core).
export const ELUR_DERIVED = Symbol.for("elur.derived");

/**
 * Pack emitido por el plugin como arg de un binding T2:
 * `__elurDerive(dep1, dep2, () => expr)` — último arg = getter original.
 * Las deps se evalúan en la posición del arg (scope de la instancia).
 */
export function __elurDerive(...args: unknown[]): ElurDerivedBinding {
  const get = args[args.length - 1] as () => unknown;
  return { [ELUR_DERIVED]: true, deps: args.slice(0, -1), get };
}

/**
 * Variante 1-dep: `__elurDerive1(dep, () => expr)` — el caso común
 * (`class=${cond(sig)}`). Sin rest array ni slice: 1 sola allocación.
 */
export function __elurDerive1(dep: unknown, get: () => unknown): ElurDerivedBinding {
  return { [ELUR_DERIVED]: true, dep, get };
}

/**
 * Núcleo T2: una edge permanente por dep señal → re-evalúa `get` y escribe
 * sólo si el resultado cambió (compare compartido — N deps, 1 write).
 * El primer `_bindSignal` escribe el valor inicial; los siguientes evalúan
 * y comparan (no-op si igual).
 *
 * Fallback: si `_bindSignal` no existe (core ≤3.5.x) o ninguna dep es
 * Signal en runtime, cae a effect+getter — las deps del getter se trackean
 * dinámicamente, semántica idéntica al path genérico.
 */
const UNSET_DERIVED = Symbol("elur-derived-unset");

// El getter T2 lee `dep.value` — si corre tracked, suscribe al consumidor
// activo (el efecto que crea la fila) a cada dep: al primer write ese efecto
// re-evalúa y dispone los bindings. Las deps ya vienen preconectadas por
// `_bindSignal`, así que la evaluación es siempre untracked.
const _untrackImpl = (_coreSignals as Record<string, unknown>).untrack as
  | (<T>(fn: () => T) => T)
  | undefined;

// `_bindDerived(dep, get, write)` — primitivo T2 del core (≥3.6): un solo
// binding con compare+untrack internos — sin el closure `run` ni arrays.
const _bindDerivedImpl = (_coreSignals as Record<string, unknown>)._bindDerived as
  | ((dep: unknown, get: () => unknown, write: (v: unknown) => void) => () => void)
  | undefined;

function bindDerived(
  packed: ElurDerivedBinding,
  write: (v: unknown) => void,
): () => void {
  const { get } = packed;
  // Fast-path 1-dep (`dep` presente, `deps` ausente): evita el array de
  // disposers y el closure `run` cuando el core expone `_bindDerived`.
  const singleDep = packed.deps === undefined;
  if (singleDep) {
    const dep = packed.dep;
    if (_bindDerivedImpl && isSignalLike(dep)) {
      return _bindDerivedImpl(dep, get, write);
    }
    if (_bindSignalImpl && isSignalLike(dep)) {
      let prev: unknown = UNSET_DERIVED;
      return _bindSignalImpl(dep, () => {
        const v = _untrackImpl ? _untrackImpl(get) : get();
        if (v !== prev) {
          prev = v;
          write(v);
        }
      });
    }
    if (!isSignalLike(dep)) {
      // Dep no-signal: el getter no tiene deps reactivas → valor estático.
      write(_untrackImpl ? _untrackImpl(get) : get());
      return () => { };
    }
    return effect(() => write(get()));
  }
  const deps = packed.deps!;
  let prev: unknown = UNSET_DERIVED;
  const run = (): void => {
    const v = _untrackImpl ? _untrackImpl(get) : get();
    if (v !== prev) {
      prev = v;
      write(v);
    }
  };
  if (_bindSignalImpl) {
    const disposers: Array<() => void> = [];
    for (const dep of deps) {
      if (isSignalLike(dep)) disposers.push(_bindSignalImpl(dep, run));
    }
    if (disposers.length > 0) {
      return () => {
        for (const d of disposers) d();
      };
    }
    // Ninguna dep resultó Signal → el set de deps del getter es vacío:
    // valor estático — una evaluación basta.
    run();
    return () => { };
  }
  return effect(() => write(get()));
}

/** C.7 T2 texto: `text.data` sigue `get()` sobre deps preconectadas. */
export function __elurBindDerivedText(
  text: Text,
  packed: ElurDerivedBinding,
): () => void {
  return bindDerived(packed, (v) => {
    text.data = v == null || v === false ? "" : (v as string);
  });
}

/** C.7 T2 attr: writer especializado (prop/attr/sanitize) sobre deps fijas. */
export function __elurBindDerivedAttr(
  element: Node,
  attrName: string,
  packed: ElurDerivedBinding,
  isUrl: boolean,
  executable: boolean,
): () => void {
  return bindDerived(
    packed,
    __elurAttrWriter(element, attrName, isUrl, executable),
  );
}

/** F4 T2: attr HTML resuelto en build — writer sin namespace/URL checks. */
export function __elurBindDerivedAttrHtml(
  element: Node,
  attrName: string,
  packed: ElurDerivedBinding,
): () => void {
  return bindDerived(packed, __elurAttrWriterHtml(element, attrName));
}

// =============================================================================
// --- C.3: fallback por binding (contextos no soportados por el path fino) ----
// =============================================================================

function isDerivedPack(v: unknown): v is ElurDerivedBinding {
  return (
    typeof v === "object" &&
    v !== null &&
    (v as Record<symbol, unknown>)[ELUR_DERIVED] === true
  );
}

/**
 * Attr genérico por binding: replica la semántica de `activateAttribute`
 * (ref, show/hide, prop DOM, sanitize URL, warn en executable) para los
 * contextos que el codegen especializado no emite inline. El template
 * alrededor sigue compilado — sólo este binding degrada.
 */
export function __elurGenericAttr(
  element: Node,
  attrName: string,
  value: unknown,
  isUrl: boolean,
  executable: boolean,
): () => void {
  const target = element as Element;

  if (attrName === "ref") {
    const reference = value as { el: Element | null };
    reference.el = target;
    return () => { reference.el = null; };
  }

  if (isDerivedPack(value)) value = value.get;
  // Core antiguo sin `_bindSignal`: la señal se normaliza al getter
  // `() => sig.value` — mismas deps que el arrow original, semántica igual.
  if (!_bindSignalImpl && isSignalLike(value)) {
    const sig = value as Signal<unknown>;
    value = () => sig.value;
  }

  if (attrName === "show" || attrName === "hide") {
    const htmlEl = target as HTMLElement;
    let originalDisplay: string | null = null;
    const writeVisible = (v: unknown): void => {
      const shouldShow = attrName === "show" ? Boolean(v) : !Boolean(v);
      if (originalDisplay === null) originalDisplay = htmlEl.style.display || "";
      htmlEl.style.display = shouldShow ? originalDisplay : "none";
    };
    if (_bindSignalImpl && isSignalLike(value)) return _bindSignalImpl(value, writeVisible);
    if (typeof value === "function") {
      let queued = false;
      let pending = false;
      let first = true;
      return effect(() => {
        pending = Boolean((value as () => unknown)());
        if (first) {
          first = false;
          writeVisible(pending);
        } else if (!queued) {
          queued = true;
          _queueDOMWrite(() => {
            queued = false;
            writeVisible(pending);
          });
        }
      });
    }
    if (!(attrName === "show" ? Boolean(value) : !Boolean(value))) {
      htmlEl.style.display = "none";
    }
    return () => { };
  }

  if (executable) {
    console.warn(
      `[elur] Dynamic binding on executable attribute "${attrName}". Use @event for handlers; avoid binding untrusted values here.`,
    );
  }

  const isDomProp = (
    attrName === "value" || attrName === "checked" || attrName === "selected"
  ) && attrName in target;

  const write = (next: unknown): void => {
    if (isDomProp) {
      (target as any)[attrName] = next ?? "";
    } else if (next == null || next === false) {
      removeAttrValue(target, attrName);
    } else {
      writeAttrValue(target, attrName, String(next), isUrl);
    }
  };

  if (_bindSignalImpl && isSignalLike(value)) return _bindSignalImpl(value, write);
  if (typeof value === "function") {
    let first = true;
    let queued = false;
    let pending: unknown;
    return effect(() => {
      pending = (value as () => unknown)();
      if (first) {
        first = false;
        write(pending);
      } else if (!queued) {
        queued = true;
        _queueDOMWrite(() => {
          queued = false;
          write(pending);
        });
      }
    });
  }
  write(value);
  return () => { };
}

/**
 * Evento directo por binding: listener con once/capture/passive +
 * prevent/stop/self — lo que el dispatcher delegado no puede honrar.
 */
export function __elurGenericEvent(
  element: Node,
  eventName: string,
  modifiers: readonly string[],
  handler: unknown,
): () => void {
  if (typeof handler !== "function") return () => { };
  const opts: AddEventListenerOptions = {
    once: modifiers.includes("once"),
    capture: modifiers.includes("capture"),
    passive: modifiers.includes("passive"),
  };
  const wrapped = (e: Event): void => {
    if (modifiers.includes("prevent")) e.preventDefault();
    if (modifiers.includes("stop")) e.stopPropagation();
    if (modifiers.includes("self") && e.target !== e.currentTarget) return;
    (handler as EventListener)(e);
  };
  element.addEventListener(eventName, wrapped, opts);
  return () => element.removeEventListener(eventName, wrapped, opts);
}

// =============================================================================
// --- C.13: hidratación compilada — activación por posición, sin scan global --
// =============================================================================

/** Rango de markers localizado posicionalmente (sin scan global). */
export interface ElurHydrateRange {
  start: Comment;
  end: Comment;
  keyed?: Array<{ start: Comment; end: Comment; serializedKey: string }>;
  array?: Array<{ start: Comment; end: Comment }>;
}

// `_hydrateNodeRange(range, value, opts, keyed, array)` — export interno del
// core (≥3.6): activa un binding de nodo sobre markers ya localizados.
const _hydrateNodeRange = (_coreHydrate as Record<string, unknown>)._hydrateNodeRange as
  | ((range: { start: Comment; end: Comment }, value: unknown, options?: unknown, keyedItems?: ElurHydrateRange["keyed"], arrayItems?: ElurHydrateRange["array"]) => (() => void) | undefined)
  | undefined;

function _hydrateMismatch(msg: string): Error {
  return new Error(`[elur] Hydration mismatch: ${msg}`);
}

/**
 * Primer Element sibling en `from` (inclusive) — salta textos y comments.
 * El cursor del hydrate compilado nunca depende de índices fijos: el HTML
 * SSR puede intercalar whitespace que el árbol compactado no tiene.
 */
export function __elurNextEl(from: Node | null): Element {
  let cur = from;
  while (cur && cur.nodeType !== 1) cur = cur.nextSibling;
  if (!cur) throw _hydrateMismatch("expected element, reached end of siblings");
  return cur as Element;
}

/**
 * Localiza `<!--elur-N-->…<!--elur-end-N-->` y los markers keyed/array del
 * rango. `from` es el primer sibling candidato (inclusive); el start marker
 * debe aparecer antes que cualquier otro boundary elur (document order).
 */
export function __elurMarkers(from: Node | null, index: number): ElurHydrateRange {
  const startName = `elur-${index}`;
  const endName = `elur-end-${index}`;
  let cur = from;
  let start: Comment | null = null;
  while (cur) {
    if (cur.nodeType === 8) {
      const data = (cur as Comment).data;
      if (data === startName) { start = cur as Comment; break; }
      if (/^elur-(end-)?\d+$/.test(data)) {
        throw _hydrateMismatch(`expected ${startName}, found ${data}`);
      }
    }
    cur = cur.nextSibling;
  }
  if (!start) throw _hydrateMismatch(`missing marker ${startName}`);
  const range: ElurHydrateRange = { start, end: start };
  scanRangeContents(start, endName, range);
  return range;
}

/**
 * Variante in-element: los markers `elur-N`/`elur-end-N` están DENTRO de
 * `el` (targets "parent"/"text" — el contenido del elemento es el binding).
 */
export function __elurMarkersIn(el: Element, index: number): ElurHydrateRange {
  return __elurMarkers(el.firstChild, index);
}

/**
 * Recorre los descendientes del rango (TreeWalker acotado al padre del
 * start) hasta `endName` en depth 0 — recoge `elur-ki:`/`elur-ke` y
 * `elur-ai`/`elur-aiend` con las mismas reglas de anidado que scanMarkers.
 */
function scanRangeContents(start: Comment, endName: string, range: ElurHydrateRange): void {
  const parent = start.parentNode;
  if (!parent) throw _hydrateMismatch("marker without parent");
  const walker = document.createTreeWalker(parent, 128 /* SHOW_COMMENT */);
  let cur: Node | null;
  do { cur = walker.nextNode(); } while (cur && cur !== start);
  if (!cur) throw _hydrateMismatch("start marker not in parent subtree");

  let depth = 0;
  const keyedStack: Array<{ start: Comment; serializedKey: string; ignored: boolean }> = [];
  const arrayStack: Array<{ start: Comment; ignored: boolean }> = [];

  while ((cur = walker.nextNode())) {
    const data = (cur as Comment).data;
    if (depth === 0 && data === endName) {
      range.end = cur as Comment;
      return;
    }
    if (/^elur-\d+$/.test(data)) { depth++; continue; }
    if (/^elur-end-\d+$/.test(data)) {
      if (depth === 0) throw _hydrateMismatch(`unexpected ${data} inside ${start.data}`);
      depth--;
      continue;
    }
    if (depth !== 0) continue;
    const ki = /^elur-ki:(.+)$/.exec(data);
    if (ki) {
      keyedStack.push({ start: cur as Comment, serializedKey: ki[1], ignored: keyedStack.length > 0 });
      continue;
    }
    if (data === "elur-ke") {
      const k = keyedStack.pop();
      if (k && !k.ignored) {
        (range.keyed ??= []).push({ start: k.start, end: cur as Comment, serializedKey: k.serializedKey });
      }
      continue;
    }
    if (data === "elur-ai") {
      arrayStack.push({ start: cur as Comment, ignored: arrayStack.length > 0 });
      continue;
    }
    if (data === "elur-aiend") {
      const a = arrayStack.pop();
      if (a && !a.ignored) {
        (range.array ??= []).push({ start: a.start, end: cur as Comment });
      }
      continue;
    }
  }
  throw _hydrateMismatch(`missing end marker ${endName}`);
}

/**
 * Activa un binding de nodo sobre un rango ya localizado. Requiere el
 * export interno `_hydrateNodeRange` del core; si falta (core antiguo) lanza
 * — hydrate() captura el error y remonta, semántica preservada.
 */
export function __elurHydrateRange(
  range: ElurHydrateRange,
  value: unknown,
  options?: unknown,
): () => void {
  if (!_hydrateNodeRange) {
    throw _hydrateMismatch("compiled hydration requires core with _hydrateNodeRange");
  }
  // Repeat dual (KeyedList + protocol): el path keyed estático de
  // hydrateNodeValue reconcilia una sola vez. Envuelto en thunk cae al
  // effect de activateNode — el getter `items` trackea `readItems` y cada
  // cambio de la lista re-reconcilia dentro del effect.
  const isDualRepeat = value != null && typeof value === "object" &&
    (value as Record<string, unknown>).__isKeyedList === true &&
    (value as Record<PropertyKey, unknown>)[ELUR_RENDER_PROTOCOL] != null;
  const hydrated = isDualRepeat
    ? () => { void (value as { items: unknown }).items; return value; }
    : value;
  return _hydrateNodeRange(range, hydrated, options, range.keyed, range.array) ?? (() => { });
}

/**
 * Localiza el root element del template dentro de `root` (top-level) o
 * dentro de `bounds` (descriptor anidado en otro binding).
 */
export function __elurHydrateRoot(
  root: ParentNode,
  bounds?: { start: Comment; end: Comment } | null,
): Element {
  if (bounds) {
    const el = __elurNextEl(bounds.start.nextSibling);
    if (!(el.compareDocumentPosition(bounds.end) & 4 /* FOLLOWING */)) {
      throw _hydrateMismatch("template root element not inside its bounds");
    }
    return el;
  }
  return __elurNextEl((root as Element).firstChild ?? null);
}
